# Generated by Django 3.1.1 on 2020-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
